title: "Harry's DevOps Portfolio"
description: "A Senior DevOps Engineer with over 11 years of experience"
url: "https://harrythedevopsguy.github.io"
baseurl: "/"
author: Harry





# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: blog
#       tags: []
#       categories: []

# plugins:
#   - jekyll-paginate

# paginate: 5  # Number of posts per page
# paginate_path: "/page/:num/"  # URL structure for paginated pages
